# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres-smit
    restart: on-failure
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER}"
    ports:
     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smit_api
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      PYTHONPATH: "${PYTHONPATH}:src"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000

networks:
  default:
      name: lan_smit
